### ISSUE TITLE
Error in loading awa_demo_data.mat file

### ISSUE THREAD

**Issue by supriya-gdptl** [hoseong-kim/sae-pytorch#2]
Hello @hoseong-kim 

Thank you for making this code and data available.

When I run the code it gives error for line 73 saying:
``
Unknown mat file type, version 117, 98
``

Could you please provide the .mat file by saving it in MATLAB v7 version?
``
save('awa_demo_data.mat','-v7')
``

**Comment by hoseong-kim** [comment]
Hello @supriya-pandhre :)

Have you tried to use the original mat file provided by Elyor Kodirov?
The download link is as follows: 
https://drive.google.com/open?id=0B3-qq6zHiDF3THJqeFhQX0hROVk

You could also visit the original GitHub repository of SAE to get further data and information:
https://github.com/Elyorcv/SAE

If it does not work, please let me know :)

**Comment by supriya-gdptl** [comment]
Thank you @hoseong-kim for the info
I have downloaded data from those links and run the code for dataset AwA and CUB but still getting the same error.
``
Unknown mat file type, version 116, 58
``

**Comment by hoseong-kim** [comment]
I've saved the mat file in MATLAB v7 version.
Please try this download link:
https://drive.google.com/open?id=1KEwChBykHwoCJRdlNERSSbioHHu9QmA-

**Comment by supriya-gdptl** [comment]
It worked. Thanks!
